name: Build
on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: read
concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:
  detect-directory-changes:
    name: "Detect Directory Changes"
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.detect.outputs.changed }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Detect Directory Changes
        id: detect
        uses: tchupp/actions-detect-directory-changes@v1.0.1

  build-template:
    needs: detect-directory-changes
    if: ${{ needs.detect-directory-changes.outputs.changed != '' && toJson(fromjson(needs.detect-directory-changes.outputs.changed)) != '[]' }}
    name: sunodo build ${{ matrix.template }}
    strategy:
      matrix:
        template: ${{ fromJSON(needs.detect-directory-changes.outputs.changed) }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: current

      - name: Install Sunodo
        run: npm install -g @sunodo/cli

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Check system requirements
        run: sunodo doctor

      - name: Build from main
        run: sunodo build
        working-directory: ${{ matrix.template }}
